export default [
  {
    "login": "y-habala",
    "id": 76556974,
    "node_id": "MDQ6VXNlcjc2NTU2OTc0",
    "avatar_url": "https://avatars.githubusercontent.com/u/76556974?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/y-habala",
    "html_url": "https://github.com/y-habala",
    "followers_url": "https://api.github.com/users/y-habala/followers",
    "following_url": "https://api.github.com/users/y-habala/following{/other_user}",
    "gists_url": "https://api.github.com/users/y-habala/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/y-habala/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/y-habala/subscriptions",
    "organizations_url": "https://api.github.com/users/y-habala/orgs",
    "repos_url": "https://api.github.com/users/y-habala/repos",
    "events_url": "https://api.github.com/users/y-habala/events{/privacy}",
    "received_events_url": "https://api.github.com/users/y-habala/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "tal7aouy",
    "id": 79597452,
    "node_id": "MDQ6VXNlcjc5NTk3NDUy",
    "avatar_url": "https://avatars.githubusercontent.com/u/79597452?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tal7aouy",
    "html_url": "https://github.com/tal7aouy",
    "followers_url": "https://api.github.com/users/tal7aouy/followers",
    "following_url": "https://api.github.com/users/tal7aouy/following{/other_user}",
    "gists_url": "https://api.github.com/users/tal7aouy/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tal7aouy/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tal7aouy/subscriptions",
    "organizations_url": "https://api.github.com/users/tal7aouy/orgs",
    "repos_url": "https://api.github.com/users/tal7aouy/repos",
    "events_url": "https://api.github.com/users/tal7aouy/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tal7aouy/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "YossefMohamed",
    "id": 47724276,
    "node_id": "MDQ6VXNlcjQ3NzI0Mjc2",
    "avatar_url": "https://avatars.githubusercontent.com/u/47724276?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/YossefMohamed",
    "html_url": "https://github.com/YossefMohamed",
    "followers_url": "https://api.github.com/users/YossefMohamed/followers",
    "following_url": "https://api.github.com/users/YossefMohamed/following{/other_user}",
    "gists_url": "https://api.github.com/users/YossefMohamed/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/YossefMohamed/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/YossefMohamed/subscriptions",
    "organizations_url": "https://api.github.com/users/YossefMohamed/orgs",
    "repos_url": "https://api.github.com/users/YossefMohamed/repos",
    "events_url": "https://api.github.com/users/YossefMohamed/events{/privacy}",
    "received_events_url": "https://api.github.com/users/YossefMohamed/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "Monayaty",
    "id": 72939693,
    "node_id": "MDQ6VXNlcjcyOTM5Njkz",
    "avatar_url": "https://avatars.githubusercontent.com/u/72939693?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Monayaty",
    "html_url": "https://github.com/Monayaty",
    "followers_url": "https://api.github.com/users/Monayaty/followers",
    "following_url": "https://api.github.com/users/Monayaty/following{/other_user}",
    "gists_url": "https://api.github.com/users/Monayaty/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Monayaty/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Monayaty/subscriptions",
    "organizations_url": "https://api.github.com/users/Monayaty/orgs",
    "repos_url": "https://api.github.com/users/Monayaty/repos",
    "events_url": "https://api.github.com/users/Monayaty/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Monayaty/received_events",
    "type": "User",
    "site_admin": false
    },
    {
    "login": "ibrahimbank",
    "id": 41842634,
    "node_id": "MDQ6VXNlcjQxODQyNjM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/41842634?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ibrahimbank",
    "html_url": "https://github.com/ibrahimbank",
    "followers_url": "https://api.github.com/users/ibrahimbank/followers",
    "following_url": "https://api.github.com/users/ibrahimbank/following{/other_user}",
    "gists_url": "https://api.github.com/users/ibrahimbank/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ibrahimbank/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ibrahimbank/subscriptions",
    "organizations_url": "https://api.github.com/users/ibrahimbank/orgs",
    "repos_url": "https://api.github.com/users/ibrahimbank/repos",
    "events_url": "https://api.github.com/users/ibrahimbank/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ibrahimbank/received_events",
    "type": "User",
    "site_admin": false
    }
];
