export default {
"login": "abdullahmoamen",
"id": 75772861,
"node_id": "MDQ6VXNlcjc1NzcyODYx",
"avatar_url": "https://avatars.githubusercontent.com/u/75772861?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/abdullahmoamen",
"html_url": "https://github.com/abdullahmoamen",
"followers_url": "https://api.github.com/users/abdullahmoamen/followers",
"following_url": "https://api.github.com/users/abdullahmoamen/following{/other_user}",
"gists_url": "https://api.github.com/users/abdullahmoamen/gists{/gist_id}",
"starred_url": "https://api.github.com/users/abdullahmoamen/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/abdullahmoamen/subscriptions",
"organizations_url": "https://api.github.com/users/abdullahmoamen/orgs",
"repos_url": "https://api.github.com/users/abdullahmoamen/repos",
"events_url": "https://api.github.com/users/abdullahmoamen/events{/privacy}",
"received_events_url": "https://api.github.com/users/abdullahmoamen/received_events",
"type": "User",
"site_admin": false,
"name": "Abdullah Moamen",
"company": 'not-yet',
"blog": "https://www.facebook.com/3bdullahmo2men/",
"location": 'banha',
"email": null,
"hireable": null,
"bio": null,
"twitter_username": '3bdullah_mo2men',
"public_repos": 25,
"public_gists": 0,
"followers": 5,
"following": 7,
"created_at": "2020-12-10T05:29:42Z",
"updated_at": "2021-04-27T12:26:14Z"
};
